name: Greetings

on:
  pull_request_target:
    types: [opened]
  issues:
    types: [opened]

jobs:
  greet-user:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
      - name: Check for prior contributions
        id: check_contributor
        run: |
          ACTOR=${{ github.actor }}
          REPO=${{ github.repository }}

          has_contributions=$(gh api "/repos/$REPO/pulls?state=all&per_page=1&creator=$ACTOR" | jq 'length')

          if [ "$has_contributions" -eq 0 ]; then
            echo "first_time=true" >> $GITHUB_OUTPUT
          else
            echo "first_time=false" >> $GITHUB_OUTPUT
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Greet first-time contributor
        if: steps.check_contributor.outputs.first_time == 'true'
        run: |
          ACTOR=${{ github.actor }}
          ISSUE_URL=${{ github.event.issue.url || github.event.pull_request.url }}

            if [ "${{ steps.check_contributor.outputs.first_time }}" = "true" ]; then
              MESSAGE="Hey @${ACTOR}, \nthanks for your first contribution! \n\nWe’ll check it out soon."
            else
              MESSAGE="Welcome back, @${ACTOR}! \n\nThanks again for contributing. We appreciate your help and check it out soon."
            fi
          gh api --method POST "$ISSUE_URL/comments" -f body="$MESSAGE"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
